a2lix_translation_form:
    locale_provider: default       
    locales: [en, nl]      
    default_locale: en            
    required_locales: [en, nl]   
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"
