vich_uploader:
    db_driver: orm

    mappings:
        artists_images:
            uri_prefix: '%app.path.artists_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.artists_images%'
            
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
